### ISSUE TITLE
CRANberries blog

### ISSUE THREAD

**Issue by theoroe3** [jumpingrivers-blog/jumpingrivers-blog.github.io#9]
@csgillespie just set up an inital CRANberries blog, got a couple comments:

It's quite difficult to comment on updated packages because you don't get information on what has changed within the files, just which files within the packages have changed. If we are looking to make this a quick weekly blog, it's gonna take too much time investigating what changes have been made specifically. 

I'd suggest instead of having a section for new packages and a section for updated packages, we have a decent sized section for new packages (with 2 packages in instead of 1) and then a tiny section on which packages have had a major update but no more than that. 

What do you think?

**Comment by csgillespie** [comment]
I was thinking of only selecting a couple of packages. Essentially every few days, have a quick skim over the new/updated packages and write a paragraph on them. So only comment on a package or two. 

Also, once it's up and running, it won't just be on you. We would each take a week. Have  think

**Comment by csgillespie** [comment]
With hindsight, this would take too much time
